// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzwKv0iMyU40uL83E-KzxXOdWStk8AseU',
    appId: '1:726764066896:web:65b66c1184b8eecf209955',
    messagingSenderId: '726764066896',
    projectId: 'durianqr-71e5f',
    authDomain: 'durianqr-71e5f.firebaseapp.com',
    storageBucket: 'durianqr-71e5f.firebasestorage.app',
    measurementId: 'G-NJGGXK7NGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gem-ogEYZJEjO-gGlyXCbl4WC80A3KE',
    appId: '1:726764066896:android:b4a75798b993c496209955',
    messagingSenderId: '726764066896',
    projectId: 'durianqr-71e5f',
    storageBucket: 'durianqr-71e5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKvCFO4R3Vk_u0rcuoQautrMok7AkhMp0',
    appId: '1:726764066896:ios:985a0a863e311107209955',
    messagingSenderId: '726764066896',
    projectId: 'durianqr-71e5f',
    storageBucket: 'durianqr-71e5f.firebasestorage.app',
    iosBundleId: 'com.example.durianQrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKvCFO4R3Vk_u0rcuoQautrMok7AkhMp0',
    appId: '1:726764066896:ios:985a0a863e311107209955',
    messagingSenderId: '726764066896',
    projectId: 'durianqr-71e5f',
    storageBucket: 'durianqr-71e5f.firebasestorage.app',
    iosBundleId: 'com.example.durianQrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzwKv0iMyU40uL83E-KzxXOdWStk8AseU',
    appId: '1:726764066896:web:1c6f11a6d7f11983209955',
    messagingSenderId: '726764066896',
    projectId: 'durianqr-71e5f',
    authDomain: 'durianqr-71e5f.firebaseapp.com',
    storageBucket: 'durianqr-71e5f.firebasestorage.app',
    measurementId: 'G-YDJC2LHKQ8',
  );
}
